#!/usr/bin/env bash

shopt -s expand_aliases

skip_ssl=${SKIP_SSL_VALIDATION:-false}
skip_ssl_flag=""

if ${skip_ssl}; then
    skip_ssl_flag="--skip-ssl-validation"
fi

echo ${CLIENT_ID}

if [[ -z "${CLIENT_ID}" ]]; then
    echo "Using admin credentials"
    alias om_cmd='om ${skip_ssl_flag} --target "${OPSMAN_URL}" --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}"'
else
    echo "Using Client-id"
    alias om_cmd='om ${skip_ssl_flag} --target "${OPSMAN_URL}" --client-id "${CLIENT_ID}" --client-secret "${CLIENT_SECRET}"'
fi
